### ISSUE TITLE
Multiplexer

### ISSUE THREAD

**Issue by fishgrind** [vortigont/ESPAsyncButton#13]
Hey,

Really enjoy your library have used it for multiple projects.

For my next project I want to expand my gpio pins using a multiplexer. How would I assign the adresses to a button as they would all use the same gpio pin.

**Comment by vortigont** [comment]
Hi! Thanks for your feedback.
I did not get an idea of a multiplexer, how exactly are going to attach multiple button to a single gpio?
I know there are i2c port expanders that are handled via i2c bus and it's own driver.

**Comment by vortigont** [comment]
With multiplexer it won't work as-is since it's the multiplexer lib to decide when and how to read it's gpio's state.
Though it is possible to create derived class from `GenericButton` that will work via expander and provide same set of events for clicks, etc...
But how it will work and if would be asynchronous is solely depends on expander's driver.

**Comment by fishgrind** [comment]
Thanks for your time. I wil look into it!
